name: swift-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["13.3.1", "13.4", "13.4.1"]
        subcommand: ["Build", "Test"]
    steps:
    - uses: actions/checkout@v3
    - name: ${{ matrix.subcommand }}
      run: |
        xcodebuild --version
        swift --version
        swift package --version
        subcommand=`echo ${{ matrix.subcommand }} | tr '[:upper:]' '[:lower:]'`
        swift $subcommand -v
      env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app