name: Release

on:
  release:
    types: [published]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.1.app

jobs:
  build-release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build for release
        run: swift build -c release
      - name: Archive the binary
        run: zip -j ponponpain.zip .build/release/ponponpain
      - name: Upload the binary
        uses: actions/upload-artifact@v3
        with:
          name: ponponpain
          path: ponponpain.zip
          retention-days: 14

  deploy-binary:
    needs: build-release
    runs-on: macos-11
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ponponpain
      - name: Deploy the binary
        uses: softprops/action-gh-release@v1
        with:
          files: ponponpain.zip